### ISSUE TITLE
MSSQL error when trying to sort on a constant value

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/databuilder#1016]
The PR to add Case to the generative tests has encountered a failing example: https://github.com/opensafely-core/databuilder/actions/runs/4104752821/jobs/7080653547#step:4:550

Translated into a spec test, the example looks like this:

```
def test_sort_by_case_column(spec_test):
    table_data = {
    e: """
          |  i1 | b1 | d1
        --+-----+----+---
        1 | 101 | T  | 1990-01-01
        1 | 102 | T  | 1991-01-01
        1 | 103 | F  | 1992-01-01
        2 | 203 | F  | 1993-01-01
        2 | 202 | T  | 1994-01-01
        2 | 201 | F  | 1995-01-01
        """,
}

    spec_test(
        table_data,
        e.sort_by(
            case(
                when(e.b1 & False).then(e.d1),  # always False
                default=None
            )
        ).first_for_patient().i1,
        {
            1: 101,
            2: 201,
        }
    )
```

The sqlite and in-memory engines return `{1: 101, 2: 201}` which implies they're sorting on `i1`; I'm not sure this is correct.
The mssql engine errors with:
```
sqlalchemy.exc.OperationalError: (pymssql._pymssql.OperationalError) (5309, b'Windowed functions, aggregates and NEXT VALUE FOR functions do not support constants as ORDER BY clause expressions.DB-Lib error message 20018, severity 16
```
If the case returns True for at least some cases, there are no errors e.g.
```
case(
        when(e.b1 & True).then(e.d1),
        default=None
    )
```

With a default value, we get the same error in mssql only, e.g.
```
case(
        when(e.b1 & False).then(e.d1),
        default=date(2000, 1, 1)
    )
```

**Comment by rebkwok** [comment]
Also passes on sqlite and in-memory engines but errors on mssql when the spec test is reduced to:
```
table_data = {
    e: """
          |  i1 
        --+-----
        1 | 101 
        """,
    }
    spec_test(
        table_data,
        e.sort_by(
            case(when(False).then(e.i1))
        ).first_for_patient().i1,
        {1: 101}
    )
```

**Comment by evansd** [comment]
> The sqlite and in-memory engines return `{1: 101, 2: 201}` which implies they're sorting on `i1`; I'm not sure this is correct.

This is actually expected behaviour and it's done so that sort operations always return consistent results even if the sort order you've specified doesn't fully determine the row order. For instance, if you get the latest even sorted by date and there are multiple events on the same date then not only will different databases give different results (which makes testing tricky) but MSSQL will pick randomly and give you a different result each time your run it which has caused problems with studies in the past.

There are two very long Github threads leading up to this conclusion which I'll link to for archaeology's sake though I wouldn't necessarily recommend reading them:
 * https://github.com/opensafely-core/databuilder/issues/461
 * https://github.com/opensafely-core/databuilder/pull/784

**Comment by evansd** [comment]
> With a default value, we get the same error in mssql only, e.g.
> ```
> case(
>         when(e.b1 & True).then(e.d1),
>         default=date(2000, 1, 1)
>     )
> ```

The above surprised me and then I found I couldn't replicate it. It seemed to execute fine on MSSQL for me. Have I missed something?

I think the solution is going to involve spotting constant expressions in sorts and replacing them with no-ops (which they effectively are anyway). MSSQL seems a bit patchy in what forms of logically constant expression it can spot. Anything involving `& False` or `| True` it seems to pick up on. But it will happily let you sort by
```py
e.b1.is_null() | e.b1.is_not_null()
```
Or by
```py
e.b1.is_null().is_not_null()
```

So our task is just to spot constant expressions at least as well as MSSQL does. We already have most of the logic for this twice over, in [`population_validatin.evaluate()`](https://github.com/opensafely-core/databuilder/blob/825252c8f47d2fc60a596b9adaea3fddd96c5953/databuilder/query_model/population_validation.py#L90) and in the in-memory query engine. (See #1019 on removing this duplication.)

But I wonder if this could be part of a more general query graph transformation step where we attempt to pre-evaluate any expressions involving constants and perform any logical simplifications. That would make solving this problem simpler and I think have other benefits as well.

**Comment by rebkwok** [comment]
> With a default value, we get the same error in mssql only, e.g.

> 
> case(
>         when(e.b1 & True).then(e.d1),
>         default=date(2000, 1, 1)
>     )
> The above surprised me and then I found I couldn't replicate it. It seemed to execute fine on MSSQL for me. Have I missed something?

That's because I mis-typed.  We get the error if the `when` is always False, so it's using the constant as the default:
```
case(
        when(e.b1 & False).then(e.d1),
        default=date(2000, 1, 1)
    )
```

**Comment by rebkwok** [comment]
#1061 is the quick fix for the generative test failures.
#1063 is the bigger issue for simplifiying constants and updating the way transforms are applies
