### ISSUE TITLE
Generative tests can trigger arithmetic overflow errors

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/databuilder#1034]
Error:

```
  File "src/pymssql/_pymssql.pyx", line 478, in pymssql._pymssql.Cursor.execute
sqlalchemy.exc.OperationalError: (pymssql._pymssql.OperationalError) (8115, b'Arithmetic overflow error converting expression to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
```

Failed test run:
https://github.com/opensafely-core/databuilder/actions/runs/4140532447/jobs/7159277900

The failed test example has a lot of nodes in it, but notably, a few `Multipy`s, which are generating very large numbers.  I could reproduce the error with this example:

```
@hyp.example(
    variable=Function.Multiply(lhs=Value(value=50000), rhs=Value(value=50000)),
    data=[]
)
```

**Comment by evansd** [comment]
Does this just end up being another addition to the list of not-very-interesting MSSQL errors that we ignore?

**Comment by rebkwok** [comment]
I think so.  That muliplication ends up in an int that's bigger than mssql's [max int](https://learn.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-ver16), so I suppose we could handle it by casting to bigint if we need to.  But I'm guessing we probably don't.

**Comment by evansd** [comment]
Yeah, there's obviously some architectural limitation of MSSQL where it can't just choose the appropriate int type for a given value like every other database. It's why you have to use a special [`COUNT_BIG()`](https://learn.microsoft.com/en-us/sql/t-sql/functions/count-big-transact-sql?view=sql-server-ver16) function if you want to count lots of things :grinning:
