### ISSUE TITLE
Ensure all QM node types are generated in standard CI run

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/databuilder#1055]
In a [standard CI run](https://github.com/opensafely-core/databuilder/blob/main/.github/workflows/main.yml#L23-L35) (which uses `just test-all`) we want to verify that all QM node types have been generated by the generative tests.  @rebkwok has verified that 200 examples is enough here, but this takes up to 60s, which is much longer than the rest of the non-Spark test suite.

So by default, `pytest` should run the generative tests with a handful of examples, and without checking that all types of node have been generated.

This means that `just test-all` should set `GENTEST_EXAMPLES` and `GENTEST_COMPREHENSIVE`, but that [by default the number of examples that hypothesis generates](https://github.com/opensafely-core/databuilder/blob/main/tests/generative/test_query_model.py#L69) should be low, eg 10.

**Comment by evansd** [comment]
45-60 seconds is still a pretty long time in the context of local test runs. I'd be reluctant to make the default generative test run any slower than it already is.

**Comment by benbc** [comment]
Can/should we distinguish between local runs and CI runs?

**Comment by evansd** [comment]
I'd say not if we can possibly help it. "Passes locally but fails in CI" is a special kind of hell.
