### ISSUE TITLE
Update arithmetic operations in generative tests to allow int constants with any numeric series

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/databuilder#1064]
Arithmetic operations that take an int literal as an input can now automatically cast it to float if necessary (see #1054).

The generative tests should reflect this, and also allow the possibility of an int `Value` input to an arithmetic operation, irrespective of the type of its other input.

Currently, strategies for arithmetic operations that take two inputs, e.g. [add](https://github.com/opensafely-core/databuilder/blob/59120a0cf762b4c167b506f136d7d63cefe60e29/tests/generative/variable_strategies.py#L254) always generate the two inputs with the same type.

The function that chooses the inputs for a binary operation is `binary_operation_with_types()`
https://github.com/opensafely-core/databuilder/blob/59120a0cf762b4c167b506f136d7d63cefe60e29/tests/generative/variable_strategies.py#L300
This generates the two inputs such that there is always at least one (non-Value) series, and those series have the required types.  In the case of an arithmetic operation, it would need to first pick the `other_series`, and if that is a `value`, pick a type for the value strategy that can be either int or float.
This might be simpler extracted to its own arithmetic binary op function.

**Comment by evansd** [comment]
No, this isn't correct. The automatic int casting is purely an ehrQL level thing; the Query Model remains strict about types (by design) and requires explicit casts still.

**Comment by rebkwok** [comment]
Ah. OK, sorry, I was confused :)
