### ISSUE TITLE
Expose `primary_diagnoses` on `hospital_admissions` table

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#1066]
Table here:
https://github.com/opensafely-core/databuilder/blob/2c53df74fdc26289c1579caa042072fa1d3c99a0/databuilder/tables/beta/tpp.py#L162-L171

And corresponding query here:
https://github.com/opensafely-core/databuilder/blob/2c53df74fdc26289c1579caa042072fa1d3c99a0/databuilder/backends/tpp.py#L179-L194

The underlying column here looks to be:
`APCS_Der.Spell_Primary_Diagnosis`

Note I deliberately used the plural because I think this can contain multiple diagnosis codes in the same way as as the `all_diagnoses` column. This is based on the way it's treated in Cohort Extractor:
https://github.com/opensafely-core/cohort-extractor/blob/52588b9518c67632ddae98780d58078c947a720d/cohortextractor/tpp_backend.py#L2573-L2581

It would be worth having a quick look at the data to confirm this.

We could then extend this utility function to allow restricting to the `primary_diagnoses` column:
https://github.com/opensafely/cis-pop-validation-ehrql/blob/be3797b185d3cde62beb63707fc4f4903de99fb0/analysis/variable_lib.py#L86-L110

Slack conversation in which this was requested:
https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1676652401134839

**Comment by milanwiedemann** [comment]
I confirm that there can be multiple primary diagnoses in `APCS_Der.Spell_Primary_Diagnosis`

**Comment by iaindillingham** [comment]
Eventually, would we want to separate each diagnosis, @evansd? At the moment, a row seems to be a semicolon delimited string (e.g. `A1;B1;C1`).

**Comment by evansd** [comment]
@iaindillingham Yes, so eventually we'd like to address this by doing two things:
1. https://github.com/opensafely-core/databuilder/issues/145
2. https://github.com/opensafely-core/databuilder/issues/574
