### ISSUE TITLE
Sketches for a better DSL

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#155]
This isn't an issue as such but I wanted a place to capture ideas that was more permanent and findable than Slack.

**Comment by evansd** [comment]
One thought I had was whether we could go down the pytest route and, instead of requiring the study author to import various things, they provide a function which accepts certain arguments and the framework then finds the function and supplies the necessary arguments.

Pros:
 * Having the study defined in a function makes it easier to reevaluate it with different configurations, e.g. as we've been wanting to do with the measure framework.
 * Avoiding importing bits of cohortextractor mean that it's possible to import the study definition without having cohortextractor installed. Importing the study definition in their analytic code is a common trick researchers use to DRY out study configuration. We've made this possible by bundling a version of cohortextractor in the Python image, but it's not kept up to date and this semi-regularly causes us grief.
 
Cons:
 * More magical implementation
 * More nesting

It's not clear to me whether the overall syntax is more or less confusing for non-Python-using study authors so I don't know what column to put that in. But it's certainly different.

Here's an example using our current class-based method:
```py
def study(tpp):
    index_date = "2020-11-01"

    class Cohort:
        _registrations = tpp.table("practice_registrations").date_in_range(index_date)
        _current_registrations = _registrations.latest("date_end")

        population = _registrations.exists()
        practice_id = _current_registrations.get("pseudo_id")

        sgss_positive = (
            tpp.table("sgss_sars_cov_2")
            .filter(positive_result=True)
            .earliest()
            .get("date")
        )

    return Cohort
```

I'm making the study take as arguments the backends its intended for, and then the tables are obtained from that backend.

Here's an example using a constructor-arguments based method as we do in cohortextractor v1. I'm using a `dict` here but obviously it could be anything:
```py
def study(tpp):
    index_date = "2020-11-01"
    registrations = tpp.table("practice_registrations").date_in_range(index_date)
    current_registrations = registrations.latest("date_end")

    return dict(
        population=registrations.exists(),
        practice_id=current_registrations.get("pseudo_id"),

        sgss_positive=(
            tpp.table("sgss_sars_cov_2")
            .filter(positive_result=True)
            .earliest()
            .get("date")
        ),
    )
```

**Comment by rebkwok** [comment]
I've been wrangling with this today, particularly around the index date, and I basically came up with your first version (although it is still importing things from cohortextractor) - this from one of the tests:

```
from cohortextractor import cohort_date_range, table

index_date_range = cohort_date_range(start="2021-01-01", end="2021-03-01", increment="month")

def cohort(index_date):

    class Cohort:
        population = table("practice_registrations").date_in_range(index_date).exists()
        date = table("clinical_events").first_by("patient_id").get("date")
        event = table("clinical_events").first_by("patient_id").get("code")

    return Cohort
```

**Comment by rebkwok** [comment]
I was concerned tha tthe nested class in a function would be too code-y for researchers though

**Comment by evansd** [comment]
Yeah, it's the "code-y-ness" problem that makes this all so tricky.

I think what you've got looks great for now though, as a way of getting measure support into v2. I think we just accept that we're going to have to iterate on this anyway and go for something which makes sense to us now and has a reasonably clean implementation.

**Comment by benbc** [comment]
@evansd I definitely think we should experiment with using functions instead of the class construct. Maybe do some user testing of various options to test our hypothesis that the class version is easier -- we wouldn't actually have to implement anything to do that testing.

On the specific question of injecting cohort extractor objects as function parameters rather than importing -- we should definitely consider it, but I don't think it would alleviate the need for importing because I think those parameters should have types, so that an IDE can provide auto-complete and other feedback (and the types would need importing). I do think, as I think we discussed before, that we should split out a library for this purpose from the main cohort extractor which just provides the DSL definition, so dependencies are minimized.
