### ISSUE TITLE
New study definition: from the point of view of a Getting Started guide

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/databuilder#190]
In v2, the Getting Started documentation will start by describing how much you can do with common / core library functions. The first study definition will look something like this (we might start with just the demographics and add the rest in step-by-step).

```py
# It's nice to have the `library.opensafely.org` hostname but realistically we're likely 
# to start with github permalinks (with SHA) from a trusted repo
demographics = cohort_from_url(
    "https://library.opensafely.org/variables/demographics/2021-11-05"
)
ons_deaths = cohort_from_url(
    "https://library.opensafely.org/variables/ons_deaths/2021-10-01"
)
clinical_codings = cohort_from_url(
    "https://library.opensafely.org/variables/clinical_codings/2021-06-20"
)


def my_study(backend):
    cohort = Cohort(backend)

    # Inclusion criteria for the cohort
    registered = demographics.registered_as_of(index_date)
    cohort.set_population(registered)

    # Common demographics
    cohort.age = demographics.age
    cohort.ethnicity = demographics.ethnicity_16_categories
    cohort.sex = demographics.sex
    cohort.died = demographics.date_of_death

    # This is to illustrate that you can get competing "facts" from different data sources
    cohort.died_ons = ons_deaths.date_of_death

    # Common clinical indicators
    cohort.chronic_cardiac_disease = clinical_codings.first_chronic_cardiac_disease_date

    return cohort


emis_and_tpp = union(emis, tpp)

# EMIS doesn't have ONS so this will fail
generate_data(my_study(emis_and_tpp))
```

**Comment by sebbacon** [comment]
The docs will then go on to explain what's inside at least the demographics example, which incidentally shows how to make custom variables. See [here](https://github.com/opensafely-core/cohort-extractor-v2/issues/181#issuecomment-944350144) for a skeleton of that.

**Comment by sebbacon** [comment]
Implementing all the above therefore implies:

* Dummy data
* Contracts for introspection of typing and backend support
* Some basic tooling for vendoring cohort snippets from a trusted location
* Most of the primitives explored in #181

**Comment by benbc** [comment]
@sebbacon How does `index_date` work in these examples? Comparing the hypothetical definition of `clinical_codings()`, makes me think that maybe the `demographics` cohort itself should be parameterized by `index_date`, rather than the variables in it, like:

```py
    registered = demographics.as_of(index_date).registered
```

_or_ we need a mechanism for defining "virtual" variables with "slots" that need filling in to reify them.

**Comment by sebbacon** [comment]
Yeh, not sure, was deliberating hand-waving, but start for 10 I had thought something like this:

```py
demographics_lib = cohort_from_url(
    "https://library.opensafely.org/variables/demographics/2021-11-05"
, index_date=index_date)

def my_study(backend, index_date:
    cohort = Cohort(backend)
    demographics = demographics_lib(backend, index_date=index_date)
```
