### ISSUE TITLE
Contracts described for a backend provider

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/databuilder#191]
A backend provider is an organisation, typically a Data Processor or a Data Controller, who can provide a database of linked clinical data that researchers might want to query using OpenSAFELY.

The benefits to a backend provider are:

* Quickly stand up a fully-documented, secure research service at low cost
* Increase the impact of the data they already host
* Access an existing community of users who are already trained in the system
* Potential for income streams to charge per-use for the service
* Well audited security practices

In order to gain all the benefits of providing a backend, in addition to installing the OpenSAFELY software, a provider must also describe their data in a format that allows researchers to write code once with the promise it can run against multiple backends.

For example, it's very common for researchers to want to query common demographics, e.g. age, sex, date of death.  OpenSAFELY promises these researchers that all compatible backends are able to supply this information. 

Additionally, backend providers may have data they wish to expose which is not common to other backends. In these cases, they must describe their data in a format that the system can use to generate documentation.

Both these requirements (declaring which common data concepts are supported; and describing novel data concepts) are met using Contracts.

Here's what the contract for core clinical events could look like, as code (we could consider an intermediate serialised format, to help decoupling subsystems?):

```py
from cohortextractor.backends import concepts

class ClinicalEvent(concepts.EventConcept):
    """The ClinicalEvent table captures clinical facts about a Person obtained in the context of examination, questioning or a procedure. It excludes medications which should be provided by the MedicationEvent table.
    """
    patient_id = concepts.Column(
        type=concepts.types.PseudoPatientId(),
        required=True,
        help="Patient's pseudonymous identifier, for linkage. You should not normally output or operate this column",
    )
    date = concepts.Column(
        type=concepts.types.Date(), Required=True, help="The date the event took place"
    )
    code = concepts.Column(
        type=concepts.types.ClinicalCode(),
        required=True,
        help="The clinical code for the event",
    )
    system = concepts.Column(
        type=concepts.types.CodingSystem(),  # A hardcoded _choices_ type, I guess?
        required=True,
        help="The coding system used for this event",
    )
    numeric_value = concepts.Column(
        type=concepts.types.Float(), required=False, min_value=0
    )
```

A backend provider can declare that their database supports these concepts like this:

```py
from cohortextractor.concepts.core.events import ClinicalEvents
clinical_events = MappedTable(
    source="TRE.ClinicalEvents",
    expected_update_frequency="monthly",
    columns=dict(
        code=Column("varchar", source="Code"),
        system=Column("varchar", source="CodingSystem"),
        date=Column("datetime", source="ConsultationDate"),
        clinical_setting=Column("varchar", source="ConsultationSetting"),
        numeric_value=Column(
            "float",
            source="NumericValue",
            backend_notes=(
                "This is never null in the underlying data; it's therefore impossible "
                "to distinguish between zero and no measurement when querying this backend" 
            ),
        ),
    ),
)
clinical_events.implements(ClinicalEvents)
```

Or they could declare that a table _extends_ a concept like this:

```py
class GraphnetClinicalEventSetting(ClinicalEvent):
    """The GraphnetClinicalEventSetting table extends ClinicalEvents with a 
    """
    clinical_setting = concepts.Column(
        type=concepts.types.Choice(values={"P", "Primary Care", "A", "Acute"}),
        required=True,
        help="Clinical setting for the event",
    )

clinical_events.implements(GraphnetClinicalEventSetting)
```

**Comment by sebbacon** [comment]
## ClinicalEvents

The ClinicalEvent table captures clinical facts about a Person obtained in the context of examination, questioning or a procedure. It excludes medications which should be provided by the MedicationEvent table.


| Column name | Description | Type | Constraints |
|--------------------|-----------------|--------|--------------|
| date                | The date the event took place| Date | Must have a value |
| code               |The clinical code for the event|ClinicalCode| Must have a value |
| system            |The coding system used for this event|CodingSystem| Must have a value |
| numeric_value ||Float|Can be empty, cannot be negative |
|clinical_setting |Clinical setting for the event|Choice|"P" for Primary Care, "A" for Acute|          



Supported by backends: [EMIS](), [TPP](), [Graphnet]()

Backend-specific notes:

Graphnet This is never null in the raw data; it's therefore impossible to distinguish between zero and no measurement

**Comment by benbc** [comment]
@sebbacon I think there is a typo in the Clinical Events generated documentation. The Graphnet backend support should say that `numerical_value` is never null, not `clinical_setting`.
