### ISSUE TITLE
Support Databricks REF and prod db

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/databuilder#206]
The REF tables have names like `SCHEMA.TABLENAME`, which the current code users.

Whereas it looks like the prod db has table names like `TABLE_dars_nic_$(agreement_number)` and no schema.

We may need to adapt the backend table/query definitions based on whether we're connecting to REF or prod. 

We could do this dynamically, by using some signal (e.g. env var) or implicit (e.g. query string heuristic).

Or, we could support it as two different backends, an NHSD-REF and NHSD-PROD, or similar.

**Comment by benbc** [comment]
I don't think we need to keep this on the backlog. If we ever come back to the NHSD backend then this problem will be obvious and we can solve it then.
