### ISSUE TITLE
Spark tests are annoyingly slow

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#248]
Prior to merging #246 the test suite took 40s to run 236 tests.; now it takes 2m 54s to run 292 tests.

I initially wondered if dropping and recreating the test tables every time was the problem so I tried removing the `metadata.drop_all(engine)` line and instead doing:
```py
for table in reversed(metadata.sorted_tables):
    session.execute(table.delete())
```

But this fails on Spark with the error:
```
DELETE is only supported with v2 tables.
```

And just eyeballing the streaming log output it looks like just the plain INSERTs are slow on Spark.

I wonder if there are configuration options we can pass to Spark of the sort that you'd never want to use in production but which will make it faster in test (I'm thinking of things like the "no fsync" option in Postgres).

**Comment by benbc** [comment]
Since the Spark tests are so slow we have never been able to run the generative tests against it. Since Graphnet are going to be using Spark it would be great to make that a first-class part of our testing.

**Comment by StevenMaude** [comment]
Somehow a few weeks ago, I stumbled on this issue and spent a quick 20-30 minutes tinkering but got nowhere.

In case no-one else spotted, there are a [bazillion configuration options](https://spark.apache.org/docs/latest/configuration.html) for Spark that control partitioning and shuffle behaviour; one of them might help.

**Comment by benbc** [comment]
@evansd do you think we should engage Hypothesis to explore the Spark configuration space? :joy:

**Comment by evansd** [comment]
:rofl: 

I think that is the only sensible solution.

**Comment by evansd** [comment]
I spent a fairly depressing Friday looking at this and getting the inverse factorial of nowhere with it. I'm going to try write up my investigations a bit more systematically than I in fact did them for the benefit of future travellers. (This will be a series of comments, rather all in one big comment.)

Here's a basic demonstration of the problem:
```console
$ pytest tests/spec/bool_series_ops/ -k 'mssql and execute'
=== 3 passed, 21 deselected in 0.48s ===

$ pytest tests/spec/bool_series_ops/ -k 'spark and execute'
=== 3 passed, 21 deselected in 10.13s ===
```

Question 1: can we figure out what Spark is doing that takes it 10 seconds?

We can watch the Spark logs while the tests runs with:
```
docker logs -f -n 1 databuilder-spark
```

This generates quite a lot of output, and also seems to show Spark pausing in various places.
We can dump the Docker logs with timestamps like this:
```sh
 start=$(date -Iseconds)
 pytest tests/spec/bool_series_ops/ -k 'spark and execute'
 docker logs --since "$start" --timestamps databuilder-spark 2> docker-logs.txt
```

I then processed this with a [Python script](https://gist.github.com/evansd/521ce3a55ac47aad58f8ecb75206219b) to look at the differences between consecutive timestamps and flag any large ones:
[`docker-logs-delta.txt`](https://github.com/opensafely-core/databuilder/files/10208335/docker-logs-delta.txt)

Picking out these and the surrounding context gives us:
```sh
grep '==>' --context 2 docker-logs-delta.txt
```
```
    03371 INFO SparkExecuteStatementOperation: Submitting query 'SELECT 'hello'' with 6965d2f7-4e0f-4a17-9690-b49313186867
    00143 INFO SparkExecuteStatementOperation: Running query with 6965d2f7-4e0f-4a17-9690-b49313186867
==> 54561 INFO SparkContext: Starting job: runInternal at Operation.java:277
    00479 INFO DAGScheduler: Got job 136 (runInternal at Operation.java:277) with 1 output partitions
    00032 INFO DAGScheduler: Final stage: ResultStage 184 (runInternal at Operation.java:277)
--
    00607 WARN HiveMetaStore: Location: file:/opt/bitnami/spark/spark-warehouse/event_level_table specified for non-external table:event_level_table
    00226 INFO FileUtils: Creating directory if it doesn't exist: file:/opt/bitnami/spark/spark-warehouse/event_level_table
==> 57166 INFO SparkExecuteStatementOperation: Submitting query 'INSERT INTO TABLE patient_level_table VALUES (1, NULL, NULL, True, NULL, NULL, CAST(NULL AS DATE), CAST(NULL AS DATE), NULL, NULL, NULL, NULL)' with 78c8cc8a-b95a-4f8b-bc69-bf08b62f2601
    00036 INFO SparkExecuteStatementOperation: Running query with 78c8cc8a-b95a-4f8b-bc69-bf08b62f2601
    02584 INFO HiveMetaStore: 7: get_database: default
--
    00022 INFO FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
    00091 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
==> 54609 INFO SparkContext: Starting job: runInternal at Operation.java:277
    00696 INFO DAGScheduler: Got job 137 (runInternal at Operation.java:277) with 1 output partitions
    00017 INFO DAGScheduler: Final stage: ResultStage 185 (runInternal at Operation.java:277)
--
    03335 INFO HiveMetaStore: 4: get_table : db=default tbl=patient_level_table
    00067 INFO audit: ugi=foo	ip=unknown-ip-addr	cmd=get_table : db=default tbl=patient_level_table	
==> 59899 INFO HashAggregateExec: spark.sql.codegen.aggregate.map.twolevel.enabled is set to true, but current version of codegened fast hashmap does not support this aggregate.
    01448 INFO SQLStdHiveAccessController: Created SQLStdHiveAccessController for session context : HiveAuthzSessionContext [sessionString=2a8c1667-cde8-4d77-998e-a137cbb275bc, clientType=HIVESERVER2]
    00032 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
--
    03741 INFO HiveMetaStore: 9: drop_table : db=default tbl=event_level_table
    00029 INFO audit: ugi=foo	ip=unknown-ip-addr	cmd=drop_table : db=default tbl=event_level_table	
==> 75224 INFO SparkExecuteStatementOperation: Submitting query '
    00025 _level_table' with e96136d8-dad5-438f-b805-769a61d3db2d
    00125 INFO SparkExecuteStatementOperation: Running query with e96136d8-dad5-438f-b805-769a61d3db2d
--
    00017 INFO DAGScheduler: Missing parents: List()
    00167 INFO DAGScheduler: Submitting ResultStage 203 (MapPartitionsRDD[633] at runInternal at Operation.java:277), which has no missing parents
==> 52045 INFO MemoryStore: Block broadcast_229 stored as values in memory (estimated size 301.1 KiB, free 363.2 MiB)
    00154 INFO BlockManagerInfo: Removed broadcast_227_piece0 on 4a06e1996a79:42411 in memory (size: 106.6 KiB, free: 365.7 MiB)
    01664 INFO BlockManagerInfo: Removed broadcast_228_piece0 on 4a06e1996a79:42411 in memory (size: 106.6 KiB, free: 365.8 MiB)
--
    05216 INFO HiveMetaStore: 2: get_table : db=default tbl=patient_level_table
    00031 INFO audit: ugi=foo	ip=unknown-ip-addr	cmd=get_table : db=default tbl=patient_level_table	
==> 63252 INFO HashAggregateExec: spark.sql.codegen.aggregate.map.twolevel.enabled is set to true, but current version of codegened fast hashmap does not support this aggregate.
    02274 INFO SQLStdHiveAccessController: Created SQLStdHiveAccessController for session context : HiveAuthzSessionContext [sessionString=babcda04-c963-484d-bd91-3e61dcbc81d4, clientType=HIVESERVER2]
    00024 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
--
    03838 INFO HiveMetaStore: 4: get_table : db=default tbl=patient_level_table
    00027 INFO audit: ugi=foo	ip=unknown-ip-addr	cmd=get_table : db=default tbl=patient_level_table	
==> 63609 INFO HashAggregateExec: spark.sql.codegen.aggregate.map.twolevel.enabled is set to true, but current version of codegened fast hashmap does not support this aggregate.
    01984 INFO SQLStdHiveAccessController: Created SQLStdHiveAccessController for session context : HiveAuthzSessionContext [sessionString=72ee00cf-928b-49c5-b85c-c04a08191b74, clientType=HIVESERVER2]
    04731 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
```

But there doesn't seem to me to be much here that's particularly illuminating to me. The slow thing is ... executing the query. Well, great.

It's somewhat interesting that `HashAggregateExec` seems to also be slow. On a whim I tried disabling the specific setting it mentions by adding these lines [here](https://github.com/opensafely-core/databuilder/blob/7e27a67379742759451fe196c1998101241cd73d/tests/lib/databases.py#L211-L212):
```
"--hiveconf",
"spark.sql.codegen.aggregate.map.twolevel.enabled=false",
```

That seemed to make things a bit slower.

**Comment by evansd** [comment]
We can have a poke around inside the container and see how it's storing the data:
```
docker exec -it databuilder-spark bash
```

It turns out the data files are here:
```console
$ docker exec databuilder-spark find /opt/bitnami/spark/spark-warehouse

/opt/bitnami/spark/spark-warehouse
/opt/bitnami/spark/spark-warehouse/event_level_table
/opt/bitnami/spark/spark-warehouse/patient_level_table
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-58239cdd-8c5e-431e-acf8-5b4130efbb0c-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-5e913ae9-164f-443e-bc38-af0b5f7a2f3e-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-81509461-baf4-4048-83b9-de86f1036ca6-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-84916b71-0712-4a63-9302-98bad92bd9fc-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-8e00c77b-91c0-4c15-a522-530e87bd70b5-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-58239cdd-8c5e-431e-acf8-5b4130efbb0c-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-e5c5f8c6-c4cc-4ed2-bcb9-24de9d4c4029-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-e464bc17-b1b4-4238-8ff3-f2c34a70ecbc-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-84916b71-0712-4a63-9302-98bad92bd9fc-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-e5c5f8c6-c4cc-4ed2-bcb9-24de9d4c4029-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-62121b80-da6f-4c53-8186-f616339cf558-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-8f677bbf-8dea-426c-80f9-b5ca7e4e8c89-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-8f677bbf-8dea-426c-80f9-b5ca7e4e8c89-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-5e913ae9-164f-443e-bc38-af0b5f7a2f3e-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-8e00c77b-91c0-4c15-a522-530e87bd70b5-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/.part-00000-62121b80-da6f-4c53-8186-f616339cf558-c000.crc
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-81509461-baf4-4048-83b9-de86f1036ca6-c000
/opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-e464bc17-b1b4-4238-8ff3-f2c34a70ecbc-c000
/opt/bitnami/spark/spark-warehouse/tempdb.db
```

On closer inspection these `part` files look like a text-based format containing exactly one patient per file:
```console
$ docker exec databuilder-spark bash -c 'head /opt/bitnami/spark/spark-warehouse/patient_level_table/*'

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-58239cdd-8c5e-431e-acf8-5b4130efbb0c-c000 <==
4\N\N\Ntrue\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-5e913ae9-164f-443e-bc38-af0b5f7a2f3e-c000 <==
7\N\Nfalsetrue\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-62121b80-da6f-4c53-8186-f616339cf558-c000 <==
5\N\N\N\N\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-81509461-baf4-4048-83b9-de86f1036ca6-c000 <==
2\N\Ntrue\N\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-84916b71-0712-4a63-9302-98bad92bd9fc-c000 <==
3\N\Ntruefalse\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-8e00c77b-91c0-4c15-a522-530e87bd70b5-c000 <==
8\N\Nfalse\N\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-8f677bbf-8dea-426c-80f9-b5ca7e4e8c89-c000 <==
6\N\N\Nfalse\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-e464bc17-b1b4-4238-8ff3-f2c34a70ecbc-c000 <==
9\N\Nfalsefalse\N\N\N\N\N\N\N

==> /opt/bitnami/spark/spark-warehouse/patient_level_table/part-00000-e5c5f8c6-c4cc-4ed2-bcb9-24de9d4c4029-c000 <==
1\N\Ntruetrue\N\N\N\N\N\N\N
```

This doesn't seem incredibly Big Data of it, as a storage strategy. Possibly there's a config setting somewhere we can tweak.

**Comment by evansd** [comment]
I tried fiddling with some [configuration options](https://spark.apache.org/docs/latest/configuration.html) to see if I could stop it making all these tiny files. I remember trying at least these and possibly some others:
```
spark.sql.shuffle.partitions=1
spark.sql.sources.bucketing.enabled=false
```

These can be applied by adding `--hiveconf` arguments [here](https://github.com/opensafely-core/databuilder/blob/7e27a67379742759451fe196c1998101241cd73d/tests/lib/databases.py#L211-L212) and killing the container with `docker rm -r databuilder-spark`, forcing it to be restarted with the new config.

Nothing seemed to make any difference: we still end up with one patient per file.

**Comment by evansd** [comment]
Simon found this repo, and associated Python tool, which might have some useful info in it but which I haven't investigated yet:
https://github.com/holdenk/spark-testing-base
https://pypi.org/project/spark-testing-base/

**Comment by evansd** [comment]
Reproducing a [helpful comment](https://stackoverflow.com/a/74878746) on StackOverflow:
> Some of this is probably intractable overhead, but the following settings can help speed up small spark tests significantly.
> ```
> "spark.sql.shuffle.partitions" = "1"
> ```
> The default shuffle partitions is 200, which creates a lot of tiny files in small tests, the effect compounds if lots of joins are done on small datasets.
> ```
> "spark.sql.autoBroadcastJoinThreshold" = "-1"
> ```
> Since your data is small all joins can be broadcast (sent to all executors instead of shuffled).
>
> See the [spark docs](https://spark.apache.org/docs/latest/configuration.html) for details of configuration options. You can set these via the cli with `--conf`, or using `.config()` on the SparkSession object when you create it.

Applying these settings seem sto reduce the time taken to run:

    pytest tests/spec/ -k 'spark and execute'

from 314s (5m14) to 255s (4m15) which is nice, although not game-changing.

**Comment by evansd** [comment]
And some follow-up [comments](https://stackoverflow.com/a/74878746) from our friend on StackOverflow:

> The above settings may not help with the simple example you give. So let's dig into that a bit.
> 
> When you run these commands:  
> 
> ```
> CREATE TABLE test (v INT);
> INSERT INTO test VALUES (1), (2), (3), (4), (5);
> ```
> 
> Spark creates a folder `test` in `/opt/spark/work-dir/spark-warehouse/` and creates 5 files, 1 per insert. For the reasons given above small files are undesirable, so we can write a single file, using a hint. 
> 
> ```
> INSERT INTO test SELECT /*+ COALESCE(1) */ * FROM VALUES (1), (2), (3), (4), (5);
> ```
> 
> Another thing we can do is mount a memory based `tmpfs` to the locations spark writes to, which should be faster than disk. 
> 
> ```
> docker run --rm --tmpfs /opt/spark/work-dir/ --tmpfs /tmp/ -i apache/spark:3.3.1 /opt/spark/bin/spark-sql < spark-test.sql
> ```
> 
> We can also try using csv instead of parquet, which is optimised for large columnar data `CREATE TABLE test (v INT) USING CSV;`. We can use also `CACHE TABLE test;` after the insert, again to keep the table in memory. 
> 
> The improvement I saw was modest ~10% in the simple example, but it may help more on your suite overall. 

I've haven't got round to trying any of these yet.

**Comment by evansd** [comment]
Some possibly useful comments in a Hacker News [thread](https://news.ycombinator.com/item?id=34609337):

> Spark makes it easy to wrap SQL in functions that are easy to test. I am the author of the popular Scala Spark (spark-fast-tests) and PySpark (chispa) testing libraries. Some additional tips to speed up Spark tests (can speed up tests between 70-90%):
> * reuse the same Spark session throughout the test suite
> 
> * Set shuffle partitions to 2 (instead of default which is 200)
> 
> * Use dependency injection to avoid disk I/O in the test suite
> 
> * Use fast DataFrame equality when possible. assertSmallDataFrameEquality is 4x faster than assertLargeDataFrameEquality. Some benchmarks here:
>    https://github.com/MrPowers/spark-fast-tests#why-is-this-library-fast
> 
> * Use column equality to test column functions. Don't compare DataFrames unless you're testing custom DataFrame transformations. See the spark-style-guide for definitions for these terms:
>   https://github.com/MrPowers/spark-style-guide/blob/main/PYSPARK_STYLE_GUIDE.md
> 
> Spark is an underrated tool for testing SQL. Spark makes it really easy to abstract SQL into unit testable chunks. Configuring your tests properly takes some knowledge, but you can make the tests run relatively quickly.

**Comment by StevenMaude** [comment]
Closing, because we removed Spark in #1136.
