### ISSUE TITLE
Azure Synapse-compatible query engine

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#483]
Graphnet use Synapse for their database. This is a data warehouse product in Azure. Synapse is supposedly SQL Server-compatible, but there are known to be some limitations to the SQL it will accept and it doesn't document a compatibility level (which implies a pretty big range of possibilities). To complicate things further there are different types of Synapse database which support different SQL features. None of this stuff is particularly well documented (or at least the documents are not easy to find).

To run the CIPHA study in Graphnet we need a query engine that is compatible with Graphnet's Synapse system. This _could_ be the `MSSQLQueryEngine`, or it could be a specialization of it.

We should try to dig out some documentation on the limitations of Synapse so that we're not trying to do anything obviously impossible. But there will probably need to be a certain amount of trial and error to get this working -- we should work with Graphnet to do this. The first thing to do is send them the SQL we generate for SQL Server and see if they can see any obvious problems -- I (Ben) will do that straight away.

**Comment by inglesp** [comment]
As a first step:

> We should try to dig out some documentation on the limitations of Synapse so that we're not trying to do anything obviously impossible.

**Comment by inglesp** [comment]
No longer required.
