### ISSUE TITLE
Consider whether other non-ehrQL features need implementing for the booster effectiveness study

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#484]
Do we need to implement other features to support this study, for example measures?

**Comment by evansd** [comment]
Interpreting "needs" strictly and saying that as long as we can extract data for the study in CSV format we're OK, I think there aren't any other features we need.

Binary output formats, dummy data validation (and indeed dummy data generation) are all high priority but not on the critical path here I think.
