### ISSUE TITLE
Put together a list of contracts that are needed for the booster effectiveness study

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#485]
Graphnet need to check that they have all the data that is needed. They also need to start to think about how to implement the contracts.

The suggested way to do this is to put together the list of contracts that the study needs and give them this along with the contract definitions. As a possible optimization, to give less work to Graphnet, we could consider implementing only the subset of the columns needed by this study in each contract.

**Comment by sebbacon** [comment]
Just dropping a link to [this old document about contracts](https://docs.google.com/document/d/1Gk66X_jNmm2g1ffr3jlfi_XzKlYcxq1Ibc-8DS0NoQE/edit#) for background reference.

**Comment by evansd** [comment]
As an initial guide to the tables needed:
```sh
rg 'patients\..+' analysis/study_definition.py \
 | sed -r 's/^.*patients\.(.+)\(.*$/\1/g' \
 | sort | uniq \
 | grep -Ev '(categorised_as|date_of|fixed_value|satisfying|minimum_of)'
```
```
address_as_of
admitted_to_hospital
age_as_of
attended_emergency_care
care_home_status_as_of
date_deregistered_from_all_supported_practices
died_from_any_cause
most_recent_bmi
registered_as_of
registered_practice_as_of
registered_with_one_practice_between
sex
with_ethnicity_from_sus
with_healthcare_worker_flag_on_covid_vaccine_record
with_test_result_in_sgss
with_these_clinical_events
with_these_codes_on_death_certificate
with_these_medications
with_tpp_vaccination_record
```

**Comment by inglesp** [comment]
I've added a list of contracts and the columns we'll need [to this spreadsheet](https://docs.google.com/spreadsheets/d/1Fu5cfmoUHGC4CY4OdEn-7rchhzjMMy--luAQJMeYlr4/edit#gid=2100914852).

We're missing a contract for SGSS test data, because I'm still confused by it.

**Comment by benbc** [comment]
There are one or two fields marked as either not required or not used by the CIPHA study. What's the reason for including those at this point?

**Comment by benbc** [comment]
We should give people at Graphhet access to the linked doc so that they can look through it for interest.

**Comment by benbc** [comment]
Do you have a plan for the SGSS data? Is it "make sure to discuss with Helen before she goes on leave"?
