### ISSUE TITLE
Ensure generative tests include all query model operations

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#511]
Associated issues which probably need addressing first:
 * https://github.com/opensafely-core/databuilder/issues/510
 * https://github.com/opensafely-core/databuilder/issues/509
 * https://github.com/opensafely-core/databuilder/issues/477
   - Note: they _do_ now hit this case but we still don't understand why they didn't before.

It would be good to have an exhuastiveness check (similar to what we have [here](https://github.com/opensafely-core/databuilder/blob/4a49fc7c72fdf1d06ae75ad01ec91455ad22749c/tests/unit/test_population_validation.py#L256-L294)) which makes sure that every new operation we add to the query model gets included in the generative tests.

Slack thread:
https://bennettoxford.slack.com/archives/C03FB777L1M/p1653563774246129

**Comment by benbc** [comment]
This has been covered by recent addition of an exhaustiveness check and specific issues for the things that aren't currently covered.
