### ISSUE TITLE
Use batch fetching and retry logic from old MSSQL engine

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#514]
Both the cohortextractor v1 and v2 MSSQL engines had code which writes results to a temporary table and then downloads them in batches with automatic retries to workaround the flakiness of the database connection. This needs porting to the new MSSQL enginge.

The code is here:
https://github.com/opensafely-core/databuilder/blob/4a49fc7c72fdf1d06ae75ad01ec91455ad22749c/databuilder/query_engines/legacy_mssql.py#L49-L81

And here:
https://github.com/opensafely-core/databuilder/blob/4a49fc7c72fdf1d06ae75ad01ec91455ad22749c/databuilder/query_engines/mssql_lib.py

We should also implement the exponential backoff logic that Peter has since added to cohortextractor v1:
 * https://github.com/opensafely-core/cohort-extractor/pull/774

**Comment by inglesp** [comment]
Have created two separate issues to track this:

* https://github.com/opensafely-core/databuilder/issues/531
* https://github.com/opensafely-core/databuilder/issues/532
