### ISSUE TITLE
Make `schema` required in query model `SelectTable`/`SelectPatientTable`

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#516]
In the early days it was convenient not to have to supply one so we made it optional:
https://github.com/opensafely-core/databuilder/blob/4a49fc7c72fdf1d06ae75ad01ec91455ad22749c/databuilder/query_model.py#L161-L172

There was also some thought that we might allow writing queries in ehrQL in a mode where you didn't need a fixed schema specified upfront.

But I now don't think this is a realistic possibility, and it would be simpler if the schema was just required. I think this is just a case of changing the signature, running the tests and finding all the places we don't currently supply one (which I'm reasonably confident will just be a handful of test cases).

**Comment by inglesp** [comment]
This is done.
