### ISSUE TITLE
Improve date handling in ehrQL

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#519]
We want to get rid of `add_days()`, `subtract_days()` and `date_difference_in_years()`, and replace them with a date delta type.

We'd like to support:

```
dataset.some_date = dataset.other_day + days(10)
dataset.some_date = dateset.other_date + days(dataset.some_integer)
dataset.age = (dataset.some_date - patients.date_of_birth).years
```

Note that we plan to make age a reusable variable.

Whoever implements this (ideally not @evansd) should discuss plan of attack with @evansd after some initial experiments.

(edited by @inglesp)

**Comment by benbc** [comment]
Current plan of record is to make age a reusable variable.
