### ISSUE TITLE
Remove need to register dataset

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#529]
Currently, users must register a dataset definition before it can be used:

```
from databuilder.definition import register

dataset = Dataset()
...
register(dataset)
```

However, this is not necessary if we require that a dataset definition has a predictable name, so we should remove it.  (Although see [this Slack thread](https://ebmdatalab.slack.com/archives/C02LEF2GC75/p1646136041149199) for arguments in favour of keeping it.)

To do this, we should:

* change [`databuilder.main.load_definition`](https://github.com/opensafely-core/databuilder/blob/main/databuilder/main.py#L80-L83) to return the module attribute called `dataset`
* display a suitable error message if the there is not a module attribute called `dataset`, or if it is not an instance of `Dataset` (errors are part of our documentation, so discuss text with @StevenMaude)
* delete [databulider/definition/](https://github.com/opensafely-core/databuilder/tree/main/databuilder/definition)
* fix up any failing tests

(Was [Review the mechanism by which Data Builder finds out about dataset definitions](https://app.shortcut.com/ebm-datalab/story/804/review-the-mechanism-by-which-data-builder-finds-out-about-dataset-definitions) in Shortcut.)

**Comment by evansd** [comment]
I think the arguments in favour of `register()` only applied in a world where you might want to register multiple datasets (e.g. one for each time period) as a way of defining measures. I now think we should do this using some form of "parameterized" dataset definition (see point 2 [here](https://github.com/opensafely-core/databuilder/issues/42#issuecomment-1085873926)) so I don't think having `register` gets us anything and I'd be happy to remove it.

If we ever decided that having multiple datasets in a single file was a useful thing to have we could support a pytest-like syntax `path/to/python_file.py::attribute_name`, but YAGNI for now.
