### ISSUE TITLE
Add exponential backoff to MSSQL engine

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#532]
To work around the flakiness of the database connection, the MSSQL engine [catches certain errors from the database, and retries twice, sleeping 0.5s between each attempt](https://github.com/opensafely-core/databuilder/blob/4a49fc7c72fdf1d06ae75ad01ec91455ad22749c/databuilder/query_engines/mssql_lib.py#L168-L181).  This is good enough to for handling temporary flakiness, but not if the database is unavailable for more than a few seconds.

Instead, we should retry with exponential backoff, with exponentially increasing sleeps between attempts.  In https://github.com/opensafely-core/cohort-extractor/pull/774 we added exponential backoff to cohort-extractor, and we should use the same approach here.  With an initial sleep of 4s, a backoff factor of 4, and making 6 retries, [our attempts are spread over 90 minutes](https://github.com/opensafely-core/cohort-extractor/blob/90f27bedede0f2780ff5ec0bc052a0a6dafe8f2d/cohortextractor/tpp_backend.py#L33-L36).

**Comment by evansd** [comment]
@Jongmassey Just noticed that this was marked in-progress, but it actually depends on this issue being closed first:

 * https://github.com/opensafely-core/databuilder/issues/531

Sorry, the dependency should have been made clear in the ticket description and wasn't!
