### ISSUE TITLE
ehrQL should automatically cast between ints and floats where necessary

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#540]
The query model is strict about types (as it should be) and so will not let you write e.g.
```py
events.take(events.numeric_value > 10)
```
And instead insists on:
```py
events.take(events.numeric_value > 10.0)
```

This is fairly user-unfriendly and it would be better if it just automatically cast the int to a float here.

[This comment](https://github.com/opensafely-core/databuilder/issues/540#issuecomment-1380150744) contains implementation notes.

**Comment by StevenMaude** [comment]
@evansd: The example given here is comparing a table value to a literal value.

Is the intent also to apply casting when working with columns?

(I've encountered this type issue and trying to explain now it in the tutorial. For now, I've put an explanation of the current state, and provided a link to this issue.)

**Comment by evansd** [comment]
Yes, I think if we're going to do this at all we should do it consistently for values drawn from any source. Though my hunch is that this is going to most often used with literal values.

**Comment by evansd** [comment]
We now have a mechanism in place (the `_cast` method, which was added to support date strings) which should allow us to support this fairly easily.


### Implementation

The implementation would look something like:
```py
class FloatFunctions(NumericFunctions):
    @staticmethod
    def _cast(value):
        if isinstance(value, int):
            return float(value)
        if isinstance(value, IntEventSeries, IntPatientSeries):
            return value.as_float()
        return value
```

And then the float [series definitions](https://github.com/opensafely-core/databuilder/blob/bb67580871f025f9df5cdcdbedc7381169788c8b/databuilder/query_language.py#L288-L293) would need changing to:
```py
class FloatEventSeries(FloatFunctions, NumericAggregations, EventSeries):
    _type = float


class FloatPatientSeries(FloatFunctions, PatientSeries):
    _type = float
```
i.e. replacing the generic `NumericFunctions` base class with `FloatFunctions`.


### Testing

As this behaviour concerns just the "ehrQL -> Query Model" translation layer it's not appropriate for the spec tests but should instead be tested in the query language unit tests. We want to test that given operands of certain types we get back a series of the type we expect (see [here](https://github.com/opensafely-core/databuilder/blob/bb67580871f025f9df5cdcdbedc7381169788c8b/tests/unit/test_query_language.py#L347-L385) for an example).


### Limitations

Note that not every form of float-int operation will be covered by this implementation. Everything in these two forms will work **(a)**:

    FloatSeries <operator> IntLiteral
    FloatSeries <operator> IntSeries

And, because of the way Python's operator overloading works, this will also work **(b)**:

    IntLiteral <operator> FloatSeries
        
But these won't **(c)**:

    IntSeries <operator> FloatSeries
    FloatLiteral <operator> IntSeries

I _think_ this is OK. The thing I think we specifically want to support is "doing int-y things to a float" (i.e. cases (a)). And we end up supporting (b) as a side-effect, but I can't see that being a very common usage. The (c) cases will require explicit casting.

If we decide that this is unacceptable then there are a couple of ways we can implement the remaining operations, which we can discuss if necessary.
