### ISSUE TITLE
Add negated variants of common methods in ehrQL

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#541]
Negation can sometimes be a bit awkward in ehrQL as it involves the slightly cryptic `~` symbol and has to go at the beginning of the method chain.

I think it would be helpful to at least add `is_not_null()` and `is_not_in()` methods. Possibly there are others but they don't immediately spring to mind.

**Comment by inglesp** [comment]
This will involve:

* Adding new methods `Series.is_not_null` and `Series.is_not_in` in [query_language.py](https://github.com/opensafely-core/databuilder/blob/main/databuilder/query_language.py).  These should return the negation of `Series.is_null` and `Series.is_in` respectively.
* Adding new spec tests `test_is_not_null` (in [tests/spec/series_ops/test_equality.py](https://github.com/opensafely-core/databuilder/blob/main/tests/spec/series_ops/test_equality.py)) and `test_is_not_in` (in [tests/spec/series_ops/test_containment.py](https://github.com/opensafely-core/databuilder/blob/main/tests/spec/series_ops/test_containment.py)).  These should follow the pattern of `test_is_null` and `test_is_in` respectively.
