### ISSUE TITLE
Critical path to running CIPHA booster effectiveness study in Graphnet

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#565]
These are the issues I think are absolutely critical to running anything:

 * https://github.com/opensafely-core/databuilder/issues/520
 * https://github.com/opensafely-core/databuilder/issues/483
 * https://github.com/opensafely-core/databuilder/issues/463
 * https://github.com/opensafely-core/databuilder/issues/485
 * https://github.com/opensafely-core/databuilder/issues/531

There are some other performance/reliability issues which we might be forced to address, or might turn out to be deferrable:

 * https://github.com/opensafely-core/databuilder/issues/532
 * https://github.com/opensafely-core/databuilder/issues/512

And there are some other issues which concern the API surface of databuilder which ideally we'd sort out before going too much further with "real study code" but aren't absolutely essential to do first:
 * https://github.com/opensafely-core/databuilder/issues/564
 * https://github.com/opensafely-core/databuilder/issues/507
 * https://github.com/opensafely-core/databuilder/issues/561
 * https://github.com/opensafely-core/databuilder/issues/527
 * https://github.com/opensafely-core/databuilder/issues/529

**Comment by inglesp** [comment]
Closing, as these issues are all labelled with the [CIPHA label](https://github.com/opensafely-core/databuilder/labels/CIPHA).
