### ISSUE TITLE
Rename `OPENSAFELY_BACKEND` env var to `DATABUILDER_BACKEND`

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#580]
As [noted](https://github.com/opensafely-core/databuilder/pull/576#issuecomment-1167540896) the `OPENSAFELY_BACKEND` env var is, although undocumented, being relied on by [user code](https://github.com/search?l=&q=org%3Aopensafely+OPENSAFELY_BACKEND&type=code) because there's currently no alternative.

It would make the process of moving from cohortextractor to databuilder easier if databuilder used a different environment variable. It's also not totally unreasonable to say that all databuilder environment variables should be prefixed `DATABUILDER_`.

**Comment by evansd** [comment]
Since adding backend "aliases" in
 * #671 
We can actually share the same environment variable between cohortextractor and databuilder because the same value can work with both e.g.
```
OPENSAFELY_BACKEND=tpp
```
It's therefore no longer obligatory to make this change before deploying.

There's still an open question as to whether it would be better to use the `DATABUILDER_` prefix. But we don't have to resolve that immediately.

**Comment by benbc** [comment]
@evansd What's your latest thinking on this?

If we go with `DATABUILDER_BACKEND`, does that mean that we need to change Job Runner to set that as well?

I'm keen to address this soon (if we do it at all) to stabilize the interface between Data Builder and the rest of OpenSAFELY.

**Comment by evansd** [comment]
I think I'd be inclined to stick with `OPENSAFELY_BACKEND`. We would, as you say, need to change Job Runner otherwise and add some extra complexity there, and it's not clear we'd gain anything by it.
