### ISSUE TITLE
Allow loading and querying of sample data

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#585]
For a more useful ehrQL tutorial (opensafely/documentation#834), it would be useful to load and process a collection of small, sample data tables into Data Builder.

This would allow:

* the tutorial author(s) to more easily verify that the code and text they are writing agrees with Data Builder's behaviour
* the tutorial reader to run examples themselves, without having to grapple with configuring a local database themselves and loading data there

Possible approach:

* There is already an `InMemorySQLiteDatabase()` used in the tests. This could be moved out to be made available to the main `databuilder` package.
* Data could be read from CSVs and loaded in, then extracted using the running in-memory database within Data Builder.
* Initially, the sample data set will be one that is provided by us. This does not yet need to be an entirely and nicely polished general-purpose data loading feature (with validation and nice user-friendly errors), but merely sufficient to allow Data Builder to run against that data.

**Comment by iaindillingham** [comment]
I think this issue has three sub-issues. I've listed them below, in order of complexity.

🙋‍♂ I'll raise this issue at tomorrow's standup.

## Verify the ehrQL code in the documentation

[snex][] extracts everything, but doesn't interpret anything. Consequently, we don't verify the ehrQL code in the documentation.

I think we should update the `extract` command (`just databuilder/extract`) to interpret the Python files in *databuilder/snippets*. However, those files are identified by passing a root directory and glob pattern to snex, via configuration. I think we need a helper script that parses snex's configuration, extracts the root directory and glob pattern, and calls `importlib.import_module` for each module it finds. The `extract` command can then call this helper script.

## Supply Data Builder with sample data

The substantive issue. I think the sample data should live with the documentation. Data Builder should be able to read the sample data and load it into an instance of `InMemorySQLiteDatabase`.

How should we store the sample data? Storing it in a CSV file would, hopefully, be good enough for now.

## Run the ehrQL code in the documentation, such that it returns sample data

Do we want the documentation to display the sample data, *à la* JupyterLab? Do we want a user to be able to interact with the sample data? How?

[snex]: https://pypi.org/project/snex/

**Comment by StevenMaude** [comment]
## Supply Data Builder with sample data

(placeholder)

**Comment by StevenMaude** [comment]
## Run the ehrQL code in the documentation, such that it returns sample data

(placeholder)

**Comment by iaindillingham** [comment]
Thanks Steve. I misunderstood the introduction to the issue:

> "For a more useful ehrQL tutorial..."

The issue is more about helping the writer/reader of the tutorial verify the code in a REPL, rather than testing the documentation ("Verify the ehrQL code in the documentation") or enhancing the documentation ("Run the ehrQL code in the documentation, such that it returns sample data").

The issue has two parts:

1. Adding the ability for Data Builder to read a CSV into a backend
2. Creating a CSV

The backend is likely to be an instance of `InMemorySQLiteDatabase` and the CSV is likely to be a patient frame.

I think @evansd is working on part one. I will return to part two, when he's done.

**Comment by StevenMaude** [comment]
Relates to #667. I think that fixes a lot of the problem there.

There's some other discussion here on using this tooling to validate and include the correct inputs/outputs which could possibly be moved to a separate issue.

**Comment by StevenMaude** [comment]
I think this is done really as far as we need for now; someone who installs Data Builder via `pip` or runs it via the OpenSAFELY CLI can, in principle (with some sticking plasters), run the tutorial dataset definitions themselves, and we're checking the inputs via the GitHub Actions workflow.

There's another question of whether we want some fancier and more interactive, but that would be some way off, and really warrants a new issue opening when/if we want this.
