### ISSUE TITLE
Support Feather v2 as an output format

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#588]
See discussion in #507.

Specifically:

> We should avoid Pandas as far as possible for this and use the PyArrow libraries directly because:
> (a) we want to stream batches to disk rather than buffer the entire result set in memory;
> (b) we want to be able to use the [32 bit date](https://arrow.apache.org/docs/python/generated/pyarrow.date32.html#pyarrow.date32) type rather than storing everything as 64-bit nanosecond precision timestamps;
> (c) all the other reason for avoiding Pandas.

This will involve updating `databuilder.main.write_dataset` to choose the output format based on the supplied filename, and to display an appropriate error if we cannot work out the output format from the filename.

**Comment by evansd** [comment]
Note we should use the `.arrow` extension rather than `.feather`. See:
https://github.com/RandomFractals/vscode-data-preview/pull/279#issuecomment-1227177351
