### ISSUE TITLE
All date operations should accept ISO date strings

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#618]
The "readable" methods on date objects (`is_after`, `is_on_or_before` etc.) already accept ISO formatted date strings as well as `datetime.date` objects. But their operator equivalents (`>`, `<=` etc) only accept date objects.

For consistency, user convenience and readability it should be possible to use ISO date strings everywhere dates are accepted.

This will involve extending the `DateFunctions` class to add re-implementations of the `__eq__`, `__ne__`, `__lt__`, `__le__`, `__gt__`, and `__ge__` methods:
https://github.com/opensafely-core/databuilder/blob/9e119166a6acfbd0ea1d211884d9c99132282d85/databuilder/query_language.py#L233

These will need to pass their argument through the `parse_date_if_str` function: 
https://github.com/opensafely-core/databuilder/blob/9e119166a6acfbd0ea1d211884d9c99132282d85/databuilder/query_language.py#L226-L230

The `is_in` method will need a bit more work because we'll have to unpack the iterable and pass each element through `parse_date_if_str`.

Once this is in place, the "readable" methods can just become aliases to their operator equivalents. For example:
https://github.com/opensafely-core/databuilder/blob/9e119166a6acfbd0ea1d211884d9c99132282d85/databuilder/query_language.py#L256-L258
Would become:
```py
def is_before(self, other):
    return self.__lt__(other)
```

**Comment by inglesp** [comment]
This will also involve adding some new spec tests to `tests/spec/date_series_ops/test_date_comparisons.py`.  These will look very similar to the existing spec tests in that file.  As well as having:

```
def test_is_before(spec_test):
    spec_test(
        table_data,
        p.d1.is_before("2000-01-01"),
        {
            1: True,
            2: False,
            3: False,
            4: None,
        },
    )
```

We'll want:

```
def test_less_than(spec_test):
    spec_test(
        table_data,
        p.d1 < "2000-01-01",
        {
            1: True,
            2: False,
            3: False,
            4: None,
        },
    )
```
