### ISSUE TITLE
Support casting between ints and floats

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#658]
Given that the query model is strict about types (to the point of not even letting you compare a float and an int) we need a way to cast between them.

In ehrQL terms we'd need to add methods called (something like) `as_int`, `as_float` to the `NumericFunctions` mixin:
https://github.com/opensafely-core/databuilder/blob/2491bb83e6b6995f570015d823c5ddd62a90800b/databuilder/query_language.py#L184

The query model will need new operations:
```py
class CastToInt(Series[int]):
    source: Series[Numeric]

class CastToFloat(Series[float]):
    source: Series[Numeric]
```

And support for these will need adding to:
```
databuilder/query_enginges/base_sql.py
databuilder/population_validation.py
tests/lib/in_memory/engine.py
```

It's a little bit clunky having an operation for each type, but I think the complexity involved into trying to make a generic `Cast` operation just isn't worth it for our use case.

There's a separate issue [here](https://github.com/opensafely-core/databuilder/issues/540) about casting automatically where the user's intention is obvious. I think we benefit overall from keeping the query model simple and strict and letting ehrQL handle these kind of UX affordances.

**Comment by evansd** [comment]
An important thing to cover in the spec tests is how rounding works when casting from float to int, particularly with negative numbers. The behaviour we want is just whatever the most common SQL behaviour is, which I think means always rounding towards zero.

**Comment by rebkwok** [comment]
Yup, those tests are what I started with.
