### ISSUE TITLE
Rework acceptance tests which use external repos

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#681]
This issue is part of [this](https://docs.google.com/document/d/1vjl4c16CDw0oJy9PQt7kQoammofeQrqzdIN_SrCunXg) initiative.

At the moment we have some acceptance tests which [pull in code](https://github.com/opensafely-core/databuilder/blob/f69754da48ddedc547fd2a421e905798a9446cce/tests/acceptance/test_age_distribution_study.py) from external repos and attempts to run it. The idea being that we should know if we've accidentally broken APIs that were actually being used.

However while our APIs are in flux, and while there are no actual studies using them, these tests make certain kinds of changes logistically painful. See related Slack thread here:
https://bennettoxford.slack.com/archives/C03FB777L1M/p1656596804056129

And even when we _do_ have stable APIs this behaviour is problematic because it makes CI non-deterministic (your PR can fail but not because of any changes within the PR itself).

As mentioned in the above thread, I think the solution is as follows:
 * acceptance test targets are vendored in to the databuilder repo, rather than being pulled in at runtime;
 * we have a script which does this vendoring and makes it easy to update the vendored version from the upstream;
 * we have a scheduled action that regularly checks out databuilder, runs the update script, and then runs the acceptance tests against the updated studies.

This final step is what guards against the vendored versions going stale, but in a way which keeps our CI runs hermetic and deterministic.

If you then need to make a breaking change to Data Builder, the process is:

1. Make the breaking change in a a PR.
2. In the same PR, make the corresponding change to the vendored dataset definition.
3. Get the PR merged.
4. Raise a PR against the original study with the same dataset definition changes.
5. Get that PR merged.
6. Run the update script to get the vendored dataset definition back in sync.

Note that there is currently only one such acceptance test, but we'll add others after this issue has been done.

**Comment by benbc** [comment]
@evansd What is the proposed workflow for making a breaking change? I haven't convinced myself that this really makes that possible.

**Comment by benbc** [comment]
Ah! Editing the vendored code hadn't occurred to me. :roll_eyes: Thanks.
