### ISSUE TITLE
Spec tests should assert that types returned by the database match the query model

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#706]
It's possible for there to be a mismatch between the type that the query model thinks an operation returns and the type actually returned by the corresponding SQL operation in the database. Usually this would be caught by the spec tests, but not always because Python is lose with comparisons between floats, ints and bools.

To ensure that the query model typing is consistent with how the databases really behave, the spec tests should ask the query model what it thinks the type is and then check that the type of the result matches.

This checking can be implemented for all tests by modifying the test harness here:
https://github.com/opensafely-core/databuilder/blob/7e27a67379742759451fe196c1998101241cd73d/tests/spec/conftest.py#L38-L42

Note that this requires a bit of rework of the test harness because currently query model compilation and query execution happens in one step here:
https://github.com/opensafely-core/databuilder/blob/7e27a67379742759451fe196c1998101241cd73d/tests/conftest.py#L62-L64

Once compiled, each variable is a `Series[T]`. The type of the series can be retrieved using [`databuilder.query_model.nodes.get_inner_type()`](https://github.com/opensafely-core/databuilder/blob/7e27a67379742759451fe196c1998101241cd73d/databuilder/query_model/nodes.py#L716). Those types can then be checked against the actual value returned by the database to ensure that they are correct.

To test that the check is working as designed, reintroduce the problem mentioned in [this comment](https://github.com/opensafely-core/databuilder/pull/704#discussion_r966066084) and ensure that the relevant specs fail with a useful error message.

**Comment by benbc** [comment]
This issue originated from a comment on an earlier PR: https://github.com/opensafely-core/databuilder/pull/704#discussion_r966066084.

**Comment by Jongmassey** [comment]
>, reintroduce the problem mentioned in https://github.com/opensafely-core/databuilder/pull/704#discussion_r966066084

Not sure how one might do that!

**Comment by Jongmassey** [comment]
@benbc with your suggested change the test I added in #881 fails, but when I revert your change the test passes. Any hints for writing a test which introduces your suggested scenario within a test and tests that the test I added failed? 

I have tried adding the following to `test_conftest.py`:

```python
@pytest.mark.xfail(strict=True)
def test_run_test_execute_type_mismatch(spec_test):
    class BadCastToInt(Series[Numeric]):
        source: Series[Numeric]
    
    class BadNumericFunctions(ComparableFunctions):
        def as_int(self):
            return _apply(BadCastToInt, self)
            
    class BadFloatPatientSeries(BadNumericFunctions, PatientSeries):
        _type = float

    @table
    class patient_level_table(PatientFrame):
        f1 = BadFloatPatientSeries()

    p = patient_level_table
    
    table_data = {
        p: """
              | f1
            --+----
            1 | 1.0
            2 | 32.3
            3 | 5.8
            4 | -6.7
            5 | -6.2
            6 |
            """,
    }

    # run a spec test with mismatching types
    spec_test(
        table_data,
        p.f1.as_int(),
        {1: 1, 2: 32, 3: 5, 4: -6, 5: -6, 6: None},
    )

```

But I'm clearly not initialising something correctly and I can't work how the various components I'm trying to replicate are initialised in the normal tests.

```
Failed: [undefined]TypeError: __init__() missing 1 required positional argument: 'qm_node'
Traceback (most recent call last):
  File "/home/jonathan/opensafely/databuilder/tests/spec/test_conftest.py", line 22, in test_run_test_execute_type_mismatch
    class patient_level_table(PatientFrame):
  File "/home/jonathan/opensafely/databuilder/tests/spec/test_conftest.py", line 23, in patient_level_table
    f1 = BadFloatPatientSeries()
TypeError: __init__() missing 1 required positional argument: 'qm_node'
```

**Comment by benbc** [comment]
@evansd could you think this through with Jon? I don't know whether it's worth the effort to write this test.

**Comment by evansd** [comment]
Yes, happy to. My instinct is that we shouldn't be meta-testing because the Philosopher in me worries about where that process stops. But @Jongmassey, grab me whenever to talk about it — you've thought about this all more recently than I have.
