### ISSUE TITLE
"Build and publish image" workflow is broken

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/databuilder#709]
The "Build and publish image" workflow is broken, so images are neither being built nor published. See, for example, [this run](https://github.com/opensafely-core/databuilder/runs/8271949455?check_suite_focus=true).

I'm unsure how to interpret the output. However, I feel this issue might be related to #702 in that the most recent tag isn't a version (`git tag --sort=refname`).

**Comment by benbc** [comment]
@iaindillingham I'm not sure what you're intending with that sort order. An hour later than you, I get this (with maybe a better sort order?):

```
> git tag --sort=-authordate | head
v0.42.0
v0.41.1
docs-metadata-b61c95630b57a844dcd72d091596e13f9ba5a4b7
docs-metadata-ae390a742a1e9796a33ab8edc6661bae7fa80023
docs-metadata-341e04ebed4f3c9cce4050ad9202adf3ac5a496e
docs-metadata-9380ab6a9bb78def8eb38c110826c280209bbec3
vnull
docs-metadata-74ff1b37ea14aa30074e740853c78b3ea2c55918
docs-metadata-c09d14221e0b1034d51dfc5e2923d41359927c4d
docs-metadata-e21427286a88da9a33babdef51fcf0b603f14b82
```

**Comment by StevenMaude** [comment]
There's something not as expected happening. For example, [this commit](https://github.com/opensafely-core/databuilder/commit/b983c78ea6fca2d751efaee8b316ab80ca2570f5) has been tagged as `v0.45.0`, and isn't on the `main` branch.

**Comment by StevenMaude** [comment]
I have a hunch it's this [action update](https://github.com/opensafely-core/databuilder/pull/689) that might be responsible, in that the timing fits with the tags going wonky.

**Comment by StevenMaude** [comment]
https://github.com/opensafely-core/databuilder/pull/714

**Comment by StevenMaude** [comment]
For reference, because I don't know if you can easily get/link from GitHub's web UI, this is the README diff for github-tag-action from 4.5 to 6.0 (with `.txt` file extension, because GitHub's file upload option requires certain extensions :man_shrugging:)

[github-tag-action.txt](https://github.com/opensafely-core/databuilder/files/9555953/github-tag-action.txt)

There's nothing immediately obvious to my eye there that breaks functionality.

There's also another [tag action](https://github.com/anothrNick/github-tag-action), which may or may not be less glitchy.

**Comment by remlapmot** [comment]
I think you want

https://github.com/mathieudutour/github-tag-action/compare/v4.5...v6.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

(GitHub reformats the URL which is `https://github.com/mathieudutour/github-tag-action/compare/v4.5...v6.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
`)

(the syntax around GitHub's 2 and 3 dot Git diff syntaxes is very poorly documented)

**Comment by StevenMaude** [comment]
This is sticking plaster fixed. The revert in #714 seems to have done the trick:

![Truncated list of GitHub Data Builder Docker images showing version 0.46.0](https://user-images.githubusercontent.com/3818079/190211815-bdd66c14-f1e3-4aa7-84ef-c7811256a8ef.png)
