### ISSUE TITLE
Database-backed tests can be slow on first run if Docker images aren't already downloaded

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#723]
Compare:

```
14 passed, 2 skipped in 363.94s (0:06:03)
```

and

```
14 passed, 2 skipped in 3.85s
```

When tests run that use a local database, they can take a long time to complete if the Docker images aren't available, depending on the speed of internet connection.

The only user feedback is just pytest sat there with a blinking cursor. A developer can investigate this by monitoring processes on their machine and see that Docker is doing things, but it's not immediately obvious.

This process might be better with some kind of warning that Docker images are being retrieved. But this may also be a "known issue/won't fix". It's worth logging here anyway, even if this issue is closed, for anyone searching in future.

**Comment by evansd** [comment]
Ah yes, I've worried about this before too. The same thing applies to the `databuilder-dev` docker image the first time that's built from scratch.

In my ideal world, the way we'd handle all these sometimes-but-not-always long running blocking steps is to spin off a timer thread beforehand which waits a few seconds and then displays a message to the user which explains what's going on. But pytest does so much monkey business with output capturing that I'm not sure how easy this is to achieve.

**Comment by evansd** [comment]
Nerdsnipped myself into implementing this:
```py
@pytest.fixture(scope="session")
def show_delayed_warning(request):
    @contextlib.contextmanager
    def create_timer(delay, message):
        def show_warning():
            capmanager = request.config.pluginmanager.getplugin("capturemanager")
            # No need to display anything if output is not being captured as the slow task
            # should be doing its own progress logging
            if capmanager.is_capturing():
                with capmanager.global_and_fixture_disabled():
                    print(message)

        timer = threading.Timer(delay, show_warning)
        timer.start()
        try:
            yield
        finally:
            timer.cancel()

    return create_timer
```

Usage:
```py
@pytest.fixture
def my_fixture(show_delayed_warning):
    with show_delayed_warning(2.0, "\nThis may take a while"):
        time.sleep(1.0)
```
