### ISSUE TITLE
Add `is_between` and `is_on_or_between` operations for dates to ehrQL

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely-core/databuilder#737]
We would like researchers to be able to write an expression like this:

```
dataset.covid_date = (
    covid_events.take(covid_events.date.is_between("2021-06-01", "2022-01-01"))
    .sort_by(covid_events.date)
    .last_for_patient()
    .date
)
```

In particular we need to add an `is_between()` method to date-typed `Series`. Like `is_after()` and others this is a date-specific synonym for a standard comparison operation, to be added to [`DateFunctions`](https://github.com/opensafely-core/databuilder/blob/6c73f9d55bdb8afdce9899411decb56e28347159/databuilder/query_language.py#L281).

```
events.date.is_between("2021-06-01", "2022-01-01")
```

is a synonym for

```
(events.date > "2021-06-01") & (events.date < "2022-01-01")
```

We also need a method `is_on_or_between()` with a similar implementation but using `>=` and `<=`.

Both new methods should accept arguments which are instances of `datetime.date`, an ISO-formatted date string, or a date-typed `Series`. (Note that there is existing machinery used in DateFunctions to provide this polymorphism.)

You should start this work by adding a failing test to the specs.

**Comment by evansd** [comment]
I think if we were being consistent with the other method names (`is_after`, `is_on_or_after` etc) then the methods would be called `is_between` and `is_on_or_between`. But the latter in particular is a bit of a mouthful.

**Comment by benbc** [comment]
@inglesp and @evansd I propose adopting `is_between()` and `is_on_or_between()` as the method names here.

I think "between" is always going to be open to misunderstanding, but hopefully having both methods and the uniformity with after/before will help. The only way I can see of avoiding the misunderstanding altogether is having mandatory extra argument like `is_between(inclusive=True)` (or equivalently `is_between_inclusive()`/`is_between_exclusive()`, which all seems too verbose to me.

Please shout if you think this is the wrong decision.

**Comment by benbc** [comment]
Original description from Caroline before I rewrote it:

---

Follow on ticket from #618 and subsequent PR #733 

Currently we can pass in date ISO strings or datetime objects into databuilder to generate `on_or_before()`, `on_or_after` type queries. We do not currently have support for events that occur with a range. For example:

```
dataset.primary_care_covid_case_0_date = (
    primary_care_covid_events.take(events.date.between(["2021-06-01", "2022-01-01"]))
    .sort_by(events.date)
    .last_for_patient()
    .date
)
```

This will involve the implementation of both `between()` and splitting the range and passing the date string through the `parse_date_if_str` function: 
https://github.com/opensafely-core/databuilder/blob/9e119166a6acfbd0ea1d211884d9c99132282d85/databuilder/query_language.py#L226-L230

**Notes:** 
_Why `between()`?_
This could be renamed. @evansd and I discussed using `is_in()` but as this is used in other place to signify that an item _is in_ a list. Therefore there are two reasons not to use this pattern. Firstly, we might want this feature with dates (for example, you could pass a list of bank holidays and ask a question about appointments on these days). Secondly, it is different from other places in the code base in terms of meaning (range vs is in a list). 

_inclusive_
We also need to make it clear to users if passing a range means that events that are on the first or last day of the range are included. Options here include:
- adding an argument `inclusive=True` 
- separate methods for each option `between_with_inclusive_dates()` or `between_without_inclusive_dates()`. or something similar. From our disucssion @evansd  (and correct if wrong) is more in favour of this option.

**Comment by Jongmassey** [comment]
for clarity, `is_between` is intended to be an open interval, and `is_on_or_between` is intended to be closed? No [half-open behaviour](http://wrschneider.github.io/2014/01/07/time-intervals-and-other-ranges-should.html)?

**Comment by evansd** [comment]
> No half-open behaviour?

I've been wondering about exactly this. It would be really good to support that if only we can come up with a sensible name for it!

**Comment by benbc** [comment]
I don't think the half-open behaviour is intuitive for dates.

**Comment by inglesp** [comment]
> I don't think the half-open behaviour is intuitive for dates.

You'd want these if you were doing several queries covering successive weeks.  However, this can be supported with `events.is_on_or_after(d1) & events.is_before(d2)`, which is probably good enough.  It's tragic that we can't support `d1 <= events < d2` though.

**Comment by Jongmassey** [comment]
>You'd want these if you were doing several queries covering successive weeks. 

I've seen this use case a lot
