### ISSUE TITLE
Boolean values in the reference/spec tests appear differently to those for the CSV query engine

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#739]
The ehrQL reference generated from the Python-based spec tests currently uses `T`, `F` to display Booleans. The CSV query engine uses `0`, `1` in its inputs and outputs. So Boolean values for the tutorial, which uses the CSV query engine, will look different to those in the ehrQL reference.

This inconsistency is probably confusing to a reader.

We're not displaying column types anywhere in those examples, just names.[^1] So what I've also just taken from this is: I should be more careful about naming in columns to try and make this clearer throughout examples, where possible.

[^1]: Associated question: is there anything we can do to help catch type errors on loading data generated from Data Builder into other analysis software?

**Comment by evansd** [comment]
We could make the CSV input and output use `T` and `F` very easily — and now I think about it we probably should. It makes it much clearer what's going on when visually scanning the CSV.

I think the only reason I went with `0` and `1` was for consistency with cohortextractor, but I don't think that's a good reason in itself. Ultimately we want to be pushing users towards typed binary formats for outputs where this question doesn't arise anyway.
