### ISSUE TITLE
`hospitalizations` has American English spelling

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#742]
At the risk of bikeshedding, do we want to use `hospitalisations`?

Or even `hospital_admissions` which seems to be the more common NHS term (assuming these two terms have the same accepted meaning)?

(Case: I am writing tutorial information referring to this term. It's a little strange to use my preferred British English spelling in the text referring to the same thing that the code spells with American English. Either you have inconsistency or there's the slight use of American English.)

It's fine if we want to retain this, but thought I'd check.

Example: https://github.com/opensafely-core/databuilder/blob/c661719bc8823b2872c79c0026a9e92415cc2c29/databuilder/contracts/wip.py#L32

**Comment by evansd** [comment]
I'd vote for `hospital_admissions` too. A general question I have about these WIP contracts is that I'm never sure which bits are the result of lots of thought and discussion and which are just how the original author happened to write them at the time. But I think we should err on the side of doing what seems right to us now.

**Comment by StevenMaude** [comment]
> But I think we should err on the side of doing what seems right to us now.

Yes, I agree.

The code is the canonical source: relevant documentation for the contracts should be generated from that. Once there's a stable implementation of the contracts which are going in now, I think they should get a final technical and clinical review/sign-off anyway.

**Comment by evansd** [comment]
> A general question I have about these WIP contracts is that I'm never sure which bits are the result of lots of thought and discussion and which are just how the original author happened to write them at the time.

After some code spelunking with @inglesp we have determined that he was the original author of these WIP contracts and that very little thought went into them. So we should feel free to amend as we see fit.

**Comment by StevenMaude** [comment]
Somehow I missed that we already have `hospital_admissions`: https://github.com/opensafely-core/databuilder/blob/6a300bc39bec4e8d37eec83051602458c3943e28/databuilder/contracts/wip.py#L21-L28

The overlap between these is not ideal.

It would be good to clarify the names of:

* `hospital_admissions` — more like "admission details"
* `hospitalizations` — code with system and date
* `hospitalizations_without_system` — just a code

From what I can see in the design documents discussing the contracts — though I may have missed something somewhere — what we have as `hospital_admissions` was first derived from HES Inpatient Spells and later referred to as "HospitalSpell" [^1]

What we have as `hospitalizations` was first referred to as "hospital administration data" as used to "inform payment".

That said, none of these seem to have a final design. So maybe the thing to do is to fix up the spelling for now, and then revisit their naming once these contracts are complete?

[^1]: Spells are a period of time spent as a patient; episodes are completed treatment under a particular consultant. From my naive reading, I'm not entirely convinced that these concepts, as in the contract here, are correctly separated (but willing to be persuaded). Here, the `hospital_admissions` table refers to a specific admission; maybe you have specific admissions per episode? But, naively, it sounds like a hospital admission would be *per* spell.
