### ISSUE TITLE
Support `weeks` as a date duration unit

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#829]
In the same way that we support `days`, `months` and `years` in #828 

This should be _relatively_ straightforward once these tickets are closed:
 * https://github.com/opensafely-core/databuilder/issues/864
 * https://github.com/opensafely-core/databuilder/issues/657

This involves adding two things:

1. Adding a `weeks()` function to go alongside `days()`, `months()`, `years()`. I think the implementation is literally just:
   ```py
   def weeks(n):
       return days(n* 7)
   ```
   Note this will need adding to the `databuilder.ehrql` module which is the public "gateway" to Data Builder.

2. Adding a `weeks` property to `DateDifference`. Again, this should just be a case of `return self.days // 7`.

As this doesn't involve changes to the query model I would suggest not adding spec tests for this and instead adding tests to `tests/unit/test_query_language.py` to ensure that ehrQL produces the expected query model structures.

**Comment by benbc** [comment]
@evansd I think I'm being dense here. Why do we need division? I thought this would be implemented using multiplication to turn the number of weeks into a number of days.

**Comment by evansd** [comment]
It's so we can do `(date1 - date2).weeks`

**Comment by benbc** [comment]
Oh right! Sorry -- for some reason I thought this was just introducing the constructor.

**Comment by evansd** [comment]
I suppose there's no reason we couldn't just do the constructor. I imagine it's the only thing that will really get used. But I'd rather do both together if we can.
