### ISSUE TITLE
Add `Case` to generative tests

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#839]
The operation needs adding to `tests.generative.variable_strategies`. If you're not familiar with the generative tests then you should get an intro from (probably) Ben before starting this work.

There is a verification step to ensure that we're including all the operations:

```
GENTEST_COMPREHENSIVE=t GENTEST_EXAMPLES=5000 just test-generative
```

Once you've added the operation you'll find that this fails. You will then need to remove `Case` from `tests.generative.test_query_model.recorder` and it should pass. If you find you've removed the last of the known_missing operations then please remove this exception mechanism altogether.

**Comment by rebkwok** [comment]
Closed by #925
