### ISSUE TITLE
`Duration`s of the same units should be add-able

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#842]
The below is reasonable code to write and it would be nice if it worked:
```py
covid_to_longcovid_lag = days(84) # 12 weeks
vaccine_effective_lag = days(14) # 2 weeks for vaccine to become effective
vaccine_to_longcovid_lag = covid_to_longcovid_lag + vaccine_effective_lag
```

We can't support adding `Duration`s in general because date addition is not associative (lolcry), but we can certainly support adding ones of the same units.

To avoid endless unit checks, first introduce unit-specific subclasses of `Duration`. This will allow simplification of the existing `Duration.__add__()` method. Then you can add to each of the subclasses' `__add__()` the ability to accept `other` as a instance of the same class.

You should include an example of this construct in the specs and provide comprehensive test coverage in `tests/unit/test_query_language.py`.

**Comment by benbc** [comment]
Note that we already have a [switch](https://github.com/opensafely-core/databuilder/blob/main/databuilder/query_language.py#L316-L324) on this "missing type" for `Duration`/`DateSeries` addition.

**Comment by Jongmassey** [comment]
Have I misunderstood the requirements or is [this](https://github.com/opensafely-core/databuilder/pull/887/commits/c1da9b6e8302dab8bc49fafc8b294982f4ca2a12) not a simple implementation that works without subclasses?
