### ISSUE TITLE
Review the syntax for setting the population on a `Dataset`

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#843]
The current syntax is:

```
dataset.set_population(<some-series>)
```

It's not clear that we arrived at this syntax through careful deliberation; it may just be the first thing that came into the head of whoever wrote the original code.

Two other possibilities are:

```
dataset.population = <some-series>
```

(This has the benefit that it is uniform with all other things that are attached to the `Dataset`. This uniformity is particularly helpful for those (many) researchers who are not Python developers and therefore have no idea that setting attributes and calling methods can have similar effects under the covers.)

```
dataset.define_population(<some-series>)
```

(This continues to mark the population as special (which it is) and avoids the jargon "set" in favour of a more domain-sympathetic term.)

The tasks for this issue are:

* reach a consensus on what the syntax should be
* change the implementation as necessary
* modify existing studies to use the new syntax
* update documentation as necessary

**Comment by inglesp** [comment]
@evansd and I have discussed this, and have settled on `dataset.define_population(...)`.

Implementation work covered by #1119.
