### ISSUE TITLE
Ensure the docs toolchain is complete and runs automatically

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#858]

**Comment by StevenMaude** [comment]
I think it's probably worth sketching out the current components of this toolchain that we have already, and then evaluating how each of those is supposed to run automatically, and whether each of those _does_ run automatically.

**Comment by benbc** [comment]
@StevenMaude I think that's a good idea. I suggest evaluating the process in terms of burden on developers (cognitive burden, time elapsed, general annoyance) rather than just automation (which is itself a means rather than an end).

**Comment by StevenMaude** [comment]
Yep, totally agree @benbc; I think that's the way to evaluate #808 too.

**Comment by StevenMaude** [comment]
As with opensafely/documentation#898, @rebkwok and I agreed that we'd defer this until after #808 — because we think that it might be simpler, should we go ahead with the full move of Data Builder documentation into the `databuilder` repository.

**Comment by StevenMaude** [comment]
@rebkwok and I think this is done. Everything seems to be in place now.

We decided that we would let others check over the new process as described in [`DEVELOPERS.md`](https://github.com/opensafely-core/databuilder/blob/9674238decf94dbe8161286487e2968f8fbffa31/DEVELOPERS.md#documentation), as a means of review. So we intend to close this issue in the next day or two, pending the outcome of that.
