### ISSUE TITLE
Support multiplication for numeric series

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#864]
This issue is part of [this](https://docs.google.com/document/d/1vjl4c16CDw0oJy9PQt7kQoammofeQrqzdIN_SrCunXg) initiative.

You should start with a spec test (see [`int_series_ops.test_arithmetic_ops`](https://github.com/opensafely-core/databuilder/blob/main/tests/spec/int_series_ops/test_arithmetic_ops.py)) and [`float_series_ops.test_arithmetic_ops`](https://github.com/opensafely-core/databuilder/blob/main/tests/spec/float_series_ops/test_arithmetic_ops.py)), which will drive out all the necessary implementation.

In ehrQL terms we'd need to add the `__mul__` method to the `NumericFunctions` mixin:
https://github.com/opensafely-core/databuilder/blob/2491bb83e6b6995f570015d823c5ddd62a90800b/databuilder/query_language.py#L184

We should also support the reverse methods `__rmul__`.

The query model will need a new `Multiply` operation:
```py
class Multiply(Series[Numeric]):
    lhs: Series[Numeric]
    rhs: Series[Numeric]
```

And support for this will need adding to:
```
databuilder/query_enginges/base_sql.py
tests/lib/in_memory/engine.py
```

After adding that you should get errors from population validation and generative test code which guide you to add support there as well.

Note that the type signature above means that we support multiplying two ints together to get another int (`2 * 3 == 6`), or two floats to get a float (`2.0 * 3.5 = 7.0`), but we don't allow multiplying an int and a float to get a float (`2 * 3.5 = 7.0`).

Instead, the user would have to explicitly cast one of the variables using either the `.to_int()` or `.to_float()` methods before multiplying. This is a bit user-hostile, but we plan to address [implicit casting](https://github.com/opensafely-core/databuilder/issues/540) separately.

**Comment by iaindillingham** [comment]
@milanwiedemann, when you merge this issue, could you move #657 from the Data Builder backlog into the next column on the Data Team board?
