### ISSUE TITLE
PyHive is currently unmaintained

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#910]
We use the PyHive library for its Spark/Hive/Databricks compatible SQLAlchemy dialect, but it currently declares itself to be unmaintained:
https://github.com/dropbox/PyHive

In concrete terms, this blocks upgrading to Python 3.10 or 3.11:
```
 tests/acceptance/comparative_booster_study/test_variables_lib.py::test_create_sequential_variables[spark]
    /home/runner/work/databuilder/databuilder/.venv/lib/python3.9/site-packages/pyhive/common.py:248: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
      elif isinstance(item, collections.Iterable):
```

And blocks upgrading to SQLAlchemy 2.0:
```
ImportError while loading conftest '/home/dave/projects/ebmdatalab/databuilder/tests/conftest.py'.
tests/conftest.py:13: in <module>
    from databuilder.query_engines.spark import SparkQueryEngine
databuilder/query_engines/spark.py:6: in <module>
    from databuilder.query_engines.spark_dialect import CreateTemporaryViewAs, SparkDialect
databuilder/query_engines/spark_dialect.py:14: in <module>
    from pyhive.sqlalchemy_hive import HiveHTTPDialect, HiveTypeCompiler, _type_map
../../../.virtualenvs/ebm-databuilder/lib/python3.9/site-packages/pyhive/sqlalchemy_hive.py:16: in <module>
    from sqlalchemy import processors
E   ImportError: cannot import name 'processors' from 'sqlalchemy' (/home/dave/.virtualenvs/ebm-databuilder/lib/python3.9/site-packages/sqlalchemy/__init__.py)
```

It's possible that these issues would be fixable without that much work, in which case forking the project might be an option. But if there's an actively maintained alternative that would be preferable.

**Comment by evansd** [comment]
Maybe worth investigating:
https://pypi.org/project/sqlalchemy-databricks/
https://github.com/crflynn/sqlalchemy-databricks

Assuming this works, it doesn't seem to take all that much code which is encouraging:
https://github.com/crflynn/sqlalchemy-databricks/blob/63caf3da49151b6ec2121960a040ea6a26608113/sqlalchemy_databricks/_dialect.py

**Comment by StevenMaude** [comment]
Closing, because we removed Spark in #1136.
