### ISSUE TITLE
Improve efficiency of generative tests by making them series-type-aware

### ISSUE THREAD

**Issue by benbc** [opensafely-core/databuilder#932]
- [x] Agree design
- [x] Extend new approach to all node types we currently support
- [ ] Experiment to see how long it now takes to generate all nodes types; can we do this as part of the standard build?
- [ ] If the answer to the last question is no, can we instead reduce the number of examples in the standard build to speed up the tests?

**Comment by benbc** [comment]
#924 introduces this approach, but is incomplete.

**Comment by rebkwok** [comment]
#990 is the last of currently-supported node types to add, but may be blocked on fixing an issue #1016 
On local runs, I'm consistentally able to get it to generate all node types with `GENTEST_EXAMPLES=200`; it usually takes something like 45-60s to run

**Comment by iaindillingham** [comment]
Closing as per [this Slack thread][1].

[1]: https://github.com/opensafely-core/databuilder/issues/1055
