### ISSUE TITLE
Automatically create issue when generative tests fail in CI

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#957]
Using [JasonEtco/create-an-issue](https://github.com/JasonEtco/create-an-issue) or another suitable action, we should create an issue against databuilder, whenever the generative tests fail in CI.

The issue should be called something like "Generative test failure on ${date}", and should contain a link to the failed CI run.

Bonus points:

* post a notification in #team-data on Slack
* add the issue to the Next column in the data team project board

In both cases, consider whether this is worth the effort before getting too bogged down here!

**Comment by evansd** [comment]
Oh interesting. I would have assumed we just wanted it posted in Slack and then we can choose if/how we want to create an issue off the back of that. Just a message saying "Generative test failure" and a link to the workflow run would do the trick.

If nothing else, preventing it creating duplicate issues each time it encounters a failure will be non-trivial.

We've already got examples of posting to Slack in the OpenPrescribing Github workflows.

**Comment by benbc** [comment]
We expect this to be fairly rare, I think, so having humans in the loop (that is, posting to Slack not Github) seems reasonable.
