### ISSUE TITLE
Generated documentation Markdown needs to be manually updated

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#967]
Following the documentation move to this repository in #938.

In the documentation repository, there were automatic pull requests to update this file. At present, developers would have to rebuild the file themselves to get the CI check to pass. 

But perhaps that's acceptable following a change to the docs, for now.

Another improvement would be to ditch this file entirely.

**Comment by StevenMaude** [comment]
Note: we're not currently enforcing the documentation checks yet, so developers don't need to have updated the `public_docs.json` to get their PRs to pass. In future, we could make this a required check to help keep the `public_docs.json` current.

**Comment by evansd** [comment]
> Another improvement would be to ditch this file entirely.

This feels like the solution to me. I think we only went down this route to try to produce a static artefact that the docs site could consume. Now that it's all in the repo I'd hope we could do without it. I'm sure that will require some re-wiring, but hopefully it will all end up simpler.

**Comment by StevenMaude** [comment]
As of #985, this will be instead that `just generate-docs` need to be run manually when changing relevant code, but this is still a simpler overall process.

That might be acceptable for the time being.

Potentially this could be a pre-commit hook, perhaps?
