### ISSUE TITLE
Improve how mkdocs-opensafely-databuilder plugin is managed

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#977]
Relates to opensafely/documentation#898.

We have to manage this as a dependency, but as it's not published on PyPI, we have to manually bump the version both here and in the documentation repository.

**Comment by rebkwok** [comment]
I think the solution is actually to get rid of it altogether, and just make the `generate_docs` script in databuilder do a little bit more work to also generate the markdown to be included rather just the json data.  The specs/backend/contacts markers in the docs then just become includes pointers to the markdown files.
