### ISSUE TITLE
Make the documentation look more in line with the main OpenSAFELY documentation

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#978]
We could:

* use a closer MkDocs configuration
* use the same OpenSAFELY theme and customisations
* consider whether the [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin#%CE%B2-development-in-imported-repos-beta)'s feature might work (it may be problematic as package versions may be out of sync)
* do a full build of the documentation that uses the parent documentation repository with the current state of the existing branch

**Comment by StevenMaude** [comment]
See also #1022.

**Comment by StevenMaude** [comment]
Using the same configuration via the multirepo-plugin doesn't work.

From #1022:

> This currently doesn't work due to a TypeError in the configuration:
> 
> ```
> TypeError: typing.Union cannot be used with isinstance()
> ```
> 
> This should disappear in Python 3.10, if MkDocs or the multirepo plugin don't ever get a patch to fix this.
> 
> Even with that patched out, the configuration is still a problem due to the macros plugin:
> 
> ```
> Traceback (most recent call last):
>   File "…/mkdocs_macros/plugin.py", line 156, in variables
>     return self._variables
> AttributeError: 'MacrosPlugin' object has no attribute '_variables'
> 
> During handling of the above exception, another exception occurred:
> …
>   File "…/mkdocs_macros/plugin.py", line 633, in on_nav
>     self.variables['navigation'] = nav
>   File "…/mkdocs_macros/plugin.py", line 158, in variables
>     raise AttributeError("Property called before on_config()")
> AttributeError: Property called before on_config()
```

**Comment by rebkwok** [comment]
Closing as I think we've got as far as we (easily) can.  I've made #1126 to revisit either the imported_docs feature or config inheritance again later.
